# -*- coding: utf-8 -*-
"""Laboratorio_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aL_qd5XJUzpI6xXt_TqAJuV96VFxtlGo
"""

import pandas as pd
import matplotlib.pyplot as plt


materias_califi = {
    'materia' : ['Matemáticas', 'Historia', 'Ciencias', 'Arte'],
    'calificación' : [85, 90, 78, 92]}


dataframe_mat = pd.DataFrame(materias_califi) #Data_frame Creación
sorted_df = dataframe_mat.sort_values(by='calificación') #Ordenamiento de el dataframe
print(dataframe_mat)

#Abajo se empieza a crear la grafica de barras, donde X es el primer elemento; Y es el segundo elemento y color es el color de la gráfica
plt.bar(materias_califi['materia'],materias_califi['calificación'], color = 'red')
plt.title("Materias_Variaciones") #Agregacion de titulo
plt.xlabel('Materias') #donde va materia = x
plt.ylabel('Calificación') #donde va Calificaciones = y
plt.savefig("Variaciones_Materias.png")
plt.show() #Mostrar el resultado

import pandas as pd
import matplotlib.pyplot as plt

asistencia_mensual = {
    'Mes' : ['Enero', 'Febrero', 'Marzo', 'Abril', 'mayo'],
    'Cantidad' : [120, 115, 130, 125, 140]}

df_asist_mens = pd.DataFrame(asistencia_mensual)
plt.plot(asistencia_mensual['Mes'], asistencia_mensual['Cantidad'], color = 'green')

import pandas as pd
import matplotlib.pyplot as plt


Edad_personas = {
    'Edades' : [12, 13, 12, 14, 13, 12, 15, 14, 13, 12]}

plt.hist(Edad_personas['Edades'], color = 'yellow', bins = 4, edgecolor = 'orange')
plt.title("Histograma_de_Edades_personas_Muestra")
plt.savefig("Histograma_de_Edades_personas_Muestra.png")
plt.show()